version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: coolKid123
      POSTGRES_PASSWORD: ${password}
    volumes:
      - ./postgres-initdb:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data
      - /etc/certs/postgres/server.crt:/:/var/lib/postgresql/server.crt:ro
      - /etc/certs/postgres/server.key:/:/var/lib/postgresql/server.key:ro
    networks:
      - garden-land
    expose:
      - 5432

  webserver:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - garden-land
    depends_on:
      - db

networks:
  garden-land:
    name: garden-land
    external: true
