version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coolKid123
      POSTGRES_PASSWORD: ${password}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - garden-land

  webserver:
    image: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - garden-land

networks:
  garden-land:
    name: garden-land
    external: true
