version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coolKid123
      POSTGRES_PASSWORD: ${password}

  webserver:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

volumes:
  - ./postgres-data:/var/lib/postgresql/data
