version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coolKid123
      POSTGRES_PASSWORD: ${password}

volumes:
  pgdata:
