version: "3"

services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - test
    env_file:
      - .env
    networks:
      - garden-land
    expose:
      - 5432

  webserver:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5432:5432"
    volumes:
      - ./frontend/dist/frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - garden-land
    depends_on:
      - db
    env_file:
      - .env

  message-server:
    container_name: garden-land
    build: .
    ports:
      - 42069:42069
    expose:
      - 42069
    networks:
      - garden-land

  bff:
    build: bff/.
    expose: 
      - 3000
    ports:
      - '3000:3000'
    networks:
      - garden-land
    env_file: .env

networks:
  garden-land:
    name: garden-land
    external: true
